apiVersion: v1
data:
  application.yml: |-
    server:
        port:  {{ .Values.service.port }}
    spring:
        application:
            name: customer-service
    management:
        security:    
             enabled: true 
    
kind: ConfigMap
metadata:
  name: cs-config