apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "customer-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "customer-service.name" . }}
    app: {{ include "customer-service.name" . }}
    version: {{ .Values.version }}
    helm.sh/chart: {{ include "customer-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "customer-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "customer-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ include "customer-service.name" . }}
        version: {{ .Values.version }}
    spec:
      volumes:
      - name: application-config
        configMap:
          name: cs-config
          items:
          - key: application.yml
            path: application.yml
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--spring.config.location=/deployments/config/application.yml"]
          volumeMounts:
          - name: application-config
            mountPath: "/deployments/config"
            readOnly: true 
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
