##################################################################################################
# Customer Service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  namespace: cna
  name: customer-service
  labels:
     app: customer-service
     version: v1
spec:
  ports:
  - nodePort: 32080
    port: 8080
    targetPort: 8080
    name: http
  selector:
    app: customer-service
  type: NodePort