apiVersion: v1
data:
  application.yml: |-
     server:
       port: 8090

         
     client:
       productservice: 
         path: http://product-service:8070
       customerservice: 
         path: http://customer-service:8080         
         
    
kind: ConfigMap
metadata:
  name: os-config
  namespace: cna