##################################################################################################
# order Service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  namespace: cna
  name: order-service
  labels:
     app: order-service
     version: v1
spec:
  ports:
  - nodePort: 32090
    port: 8090
    targetPort: 8090
    name: http
  selector:
    app: order-service
  type: NodePort