##################################################################################################
# product Service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  namespace: cna
  name: product-service
  labels:
     app: product-service
     version: v1
spec:
  ports:
  - nodePort: 32070
    port: 8070
    targetPort: 8070
    name: http
  selector:
    app: product-service
  type: NodePort