version: '2'
services:


#### Infrastructure Tools   ####
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "orders:3:1"
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    command: elasticsearch
    mem_limit: "1024m"  
    ports:
     - "9200:9200"
     - "9300:9300"
  
  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    hostname: "logstash"
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
     - ./logstash/config:/etc/logstash/conf.d
    ports:
     - "5000:5000"
  
  
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    environment:
     - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
     - "5601:5601"
     
     
  zipkin:
    image: openzipkin/zipkin
    mem_limit: "512m"  
    ports:
      - 9411:9411
      
#### CNA Services   ####      
      
  config-server:
        image: cna-config-server:v1
        ports:
        - 8888:8888
        environment:
            PROFILE: native
            MEM_ARGS:   "-Xmx320m"     
            
  discovery-server:
        image: cna-discovery-server:v1
        ports:
        - 8761:8761
        environment:
            PROFILE: native
            MEM_ARGS:   "-Xmx320m"     
            
  edge-gateway:
        image: cna-edge-gateway:v1
        depends_on:
        - config-server
        - discovery-server
        ports:
        - 9999:9999
        environment:
            PROFILE: docker
            MEM_ARGS:   "-Xmx320m"     
            
  customer-service:
        image: cna-customer-service:v1
        depends_on:
        - config-server
        - discovery-server
        environment:
            PROFILE: docker
            MEM_ARGS:   "-Xmx320m"     
            
  order-service:
        image: cna-order-service:v1
        depends_on:
        - config-server
        - discovery-server
        - kafka
        environment:
            MEM_ARGS:   "-Xmx320m"         
            PROFILE: docker 

  rating-service:
        image: cna-rating-service:v1
        depends_on:
        - config-server
        - discovery-server
        - kafka
        environment:
            MEM_ARGS:   "-Xmx320m"         
            PROFILE: docker 
            
            
  product-service:
        image: cna-product-service:v1
        depends_on:
        - config-server
        - discovery-server
        environment:
            PROFILE: docker 
            MEM_ARGS:   "-Xmx320m"     
                                                         