version: '2'
services:


#### Infrastructure Tools   ####
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    command: elasticsearch
    ports:
     - "9200:9200"
     - "9300:9300"
  
  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    hostname: "logstash"
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
     - ./logstash/config:/etc/logstash/conf.d
    ports:
     - "5000:5000"
  
  
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    environment:
     - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
     - "5601:5601"
     
     
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411