server:
    port: 8082
spring:
    application:
        name: customer-service
    boot:
        admin:
             url: http://localhost:6789
             
management:
  security:
    enabled: false             
               
        
        
