apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: cna
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
  selector:
    app: zookeeper
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cna
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zookeeper
        tier: backend
    spec:
      containers:
      - image: wurstmeister/zookeeper
        name: zookeeper
        ports:
        - containerPort: 2181
          name: zookeeper
          
          
---

apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: cna
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
  selector:
    app: kafka
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cna
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
        tier: backend
    spec:
      hostname: kafka
      containers:
      - image: wurstmeister/kafka
        name: kafka
        livenessProbe:
          exec:
           command:
           - sh
           - -c
           - "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server=kafka:9092"
          initialDelaySeconds: 70      
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092  
        - name: KAFKA_CREATE_TOPICS
          value:  "user_create:1:1"  
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value:  "15000" 
        ports:
        - containerPort: 9092
          name: kafka          
