server:
  port: 8084

spring:
  application:
    name: rating-service
  boot:
        admin:
             url: http://localhost:6789
             
management:
  security:
    enabled: false             
               
        
kafka:
  consumer:
    bootstrap: localhost:9092 # kafka
    group: WorkUnitApp
    topic: orders    