apiVersion: v1
data:
  application.yml: |-
     server:
       port: 8084
     spring:
       application:
         name: rating-service
     kafka:
       consumer:
         bootstrap: kafka:9092 
         group: WorkUnitApp
         topic: orders    
    
kind: ConfigMap
metadata:
  name: rs-config
  namespace: cna
