##################################################################################################
# Rating Service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  namespace: cna
  name: rating-service
  labels:
     app: rating-service
     version: v1
spec:
  ports:
  - nodePort: 32084
    port: 8084
    targetPort: 8084
    name: http
  selector:
    app: rating-service
  type: NodePort
