apiVersion: v1
data:
  application.yml: |-
     server:
       port: 8085
     spring:
       application:
         name: order-service
         
     client:
       productservice: 
         path: http://product-service:8083
       customerservice: 
         path: http://customer-service:8082         
         
     kafka:
       producer:
          bootstrap: kafka:9092
          topic: orders
    
kind: ConfigMap
metadata:
  name: os-config
  namespace: cna
