##################################################################################################
# Order Service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  namespace: cna
  name: order-service
  labels:
     app: order-service
     version: v1
spec:
  ports:
  - nodePort: 32085
    port: 8085
    targetPort: 8085
    name: http
  selector:
    app: order-service
  type: NodePort
