server:
    port: 8083
spring:
    application:
        name: product-service-v2
    boot:
        admin:
             url: http://localhost:6789
             
management:
  security:
    enabled: false             
                       