spring:
  application:
    name: order-service
  boot:
        admin:
             url: http://localhost:6789
             
management:
  security:
    enabled: false             
               
client:
    productservice: 
        path: http://localhost:8083
    customerservice: 
        path: http://localhost:8082
kafka:
  producer:
    bootstrap: localhost:9092 #kafka:9092
    topic: orders