apiVersion: v1
data:
  application.yml: |-
    server:
        port: 8083
    spring:
        application:
            name: product-service
    management:
        security:    
             enabled: false 
    
kind: ConfigMap
metadata:
  name: ps-config
  namespace: cna
