##################################################################################################
# Product Service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  namespace: cna
  name: product-service-v2
  labels:
     app: product-service
spec:
  ports:
  - port: 8083
    targetPort: 8083
    name: http
  selector:
    app: product-service
    version: v2