---
apiVersion: v1
kind: ConfigMap
metadata:
    name: traefik-configmap
    namespace: kube-system
data:
    traefik.toml: |
      [tracing]
         backend = "zipkin"
         serviceName = "gateway"
         spanNameLimit = 150
         [tracing.zipkin]
             httpEndpoint = "http://zipkin:9411/api/v1/spans"
             debug = false
             sameSpan = false
             id128Bit = true