##################################################################################################
# Customer Service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  namespace: cna
  name: customer-service
  labels:
     app: customer-service
     version: v1
spec:
  ports:
  - nodePort: 32082
    port: 8082
    targetPort: 8082
    name: http
  selector:
    app: customer-service
  type: NodePort
